# This file allows you to configure your python environment quickly for prednet.
# Please refer to the conda documentation for more info:
# https://conda.io/docs/user-guide/tasks/manage-environments.html

name: prednet

channels:
  - defaults

dependencies:
  - python=3.6.13
  - keras==2.2.4
  - tensorflow-gpu==1.12.0
  - matplotlib
  - pandas
  - pip:
    - hickle==3.4.5